/**
 * @file mdm.lang.de.js
 * @author Stefan Wilhelm (cerbero s@atwillys.de)
 * @license CC BY-NC-SA 4.0 (https://creativecommons.org/licenses/by-nc-sa/4.0/)
 */
 ;(function() { util.global("mdm-config",{}).lang = { localizations: { "de": {

  // Char-Sheet fixed abbreviation/key replacements. Translations, skills, spells, etc with the same keys
  // are considered invalid.
  abbr: {
    "k": "Körper", "m": "Motorik", "b": "Bewusstsein", "g": "Geist", "i": "Intellekt", "c": "Charakter",
    "kr": "Kraft", "gw": "Gewandtheit", "gs": "Geschick", "re": "Reaktion", "wa": "Wahrnehmung", "in": "Intuition",
    "ma": "Magie", "ke": "Kreativität", "wi": "Wissen", "mn": "Manipulation", "wk": "Willenskraft", "au": "Auftreten",
    "lp": "Lebenspunkte", "mp": "Magiepunkte", "hn": "Handlungen", "mr": "Magieresistenz", "ab": "Aktionsbasis",
    "rlp": "Regeneration LP", "rmp": "Regeneration MP", "ap": "Ausdauerpunkte", "rf": "Reflex", "mu": "Mut",
    "ns": "Schwere Waffen", "nm": "Mittelschwere Waffen", "nl": "Leichte Waffen", "nw": "Waffenloser Kampf",
    "ff": "Fernkampfwaffen", "xp": "Erfahrung", "at": "Attacke", "pa": "Parade", "rs": "Rüstungsschutz",
    "be": "Behinderung", "fk": "Fertigkeit", "kt": "Kampftechnik", "ms": "Magieschule", "kd": "Kampfdisziplin",
    "pm": "Persönlichkeitsmerkmal", "es": "Eigenschaft", "bs": "Basisschaden", "ks": "Krit-Schaden", "zs": "Zusatz-Schaden"
  },

  // Word/key based translation
  translations: {
    // General /Fixed terms
    "name": [ "Name", "" ],
    "race": [ "Rasse", "" ],
    "features": [ "Persönlichkeitsmerkmale", "Abstrakte, allgemeine Werte, die den Charakter im Kern beschreiben. Werden selten direkt im Spiel verwendet, sondern dienen zum Berechnen speziellerer Werte." ],
    "properties": [ "Eigenschaften", "Charakterwerte, die Fähigkeiten/Fitness in verschiedenen Bereichen darstellen. Werden oft für Proben herangezogen." ],
    "attributes": [ "Attribute", "Aus Persönlichkeitsmerkmalen und Eigenschaften errechnete Werte, die im Spiel oft verwendet werden und den Spielablauf vereinfachen/beschleunigen." ],
    "skills": [ "Fertigkeiten", "Gelernte, antrainierte, oder durch Begabung vorhandene Spezialisierungen, die zur Verbesserung von Proben mit angerechnet werden." ],
    "tactics": [ "Kampftechniken", "Durch Kampferfahrung erworbene Techniken und Spezial-Attacken, die mit körperlicher Verausgabung angewendet werden können." ],
    "armor-head": "Kopfschutz",
    "armor-arms": "Armschutz",
    "armor-torso": "Torsoschutz",
    "armor-legs": "Beinschutz",
    "armor-shield": "Schildschutz",
    "weapon-at": "Angriff",
    "weapon-effects": "Effekte",
    "spell-cost": "Spruchkosten",
    "spell-duration": "Wirkungsdauer",
    "spell-range": "Reichweite",
    "spell-damage": "Schaden",
    "spell-check": "Magieprobe",
    "spell-casttime": "Sprechdauer",
    "skill-effects": "Effekte",
    "skill-refs": "Passend",
    "skill-modifies": "Bewirkt",
    "tactic-weapons": "Gilt für",
    "tactic-ap": "AP",
    "tactic-effect": "Bewirkt",
    "tactic-condition": "Bedingung",
    "race-pm": "PM",
    "race-es": "ES",
    "race-at": "AT",
    "race-fk": "FK",
    "bestiary-presence": "Vorkommen",
    "bestiary-attributes": "Attribute",
    "bestiary-capabilities": "Besonderheiten",
    "bestiary-armor": "Rüstung",
    "bestiary-attack": "Angriff",
    "bestiary-attack1": "Angriff 1",
    "bestiary-attack2": "Angriff 2",
    "bestiary-attack3": "Angriff 3",
    "bestiary-attack4": "Angriff 4",
    // Races
    "no-race": [ " ", "Keine Rasse ausgewählt, das solltest du noch tun." ],
    "human": [ "Mensch", "Menschliche Person ohne spezielle kulturelle oder körperliche Ausprägung." ],
    "dwarf": [ "Zwerg", "Zwergische Person ohne spezielle kulturelle oder körperliche Ausprägung." ],
    "elf": [ "Elf", "Elvische Person ohne spezielle kulturelle oder körperliche Ausprägung." ],
    "orc": [ "Orc", "Orcische Person ohne spezielle kulturelle oder körperliche Ausprägung." ],
    "goblin": [ "Goblin", "Normaler Goblin ohne spezielle kulturelle oder körperliche Ausprägung." ],
    "human-midland" : [ "Mittelländer", "Mensch aus dem Mittelreich." ],
    "human-northland": [ "Nordländer", "Mensch aus den Nordlanden." ],
    "human-southland" : [ "Südländer", "Mensch aus den Südlanden" ],
    "human-westland" : [ "Westmensch", "Mensch aus dem Westen" ],
    "human-desert" : [ "Wüstling", "Mensch, der in der Großen Wüste beheimatet ist" ],
    "elf-forest": [ "Waldelf", "Elf aus den (meist nördlichen) Wäldern Ganthors" ],
    "elf-ice": [ "Eiself", "Aus den nördlichen Eislanden abstammender Elf" ],
    "elf-wind": [ "Windelf", "Von den Windinseln abstammender Elf" ],
    "dwarf-hill" : [ "Hügelzwerg", "Zwerg aus den Hügellanden" ],
    "dwarf-gray" : [ "Grauzwerg", "Zwerg aus den Massiv des Großen Rückens" ],
    "dwarf-red" : [ "Rotbart", "Zwerg vom den Rotbart-Clans im Großen Rücken" ],
    "halfling" : [ "Halbling", "Halbling, meist aus der Nähe des Großen Kraters" ],
    "half-elf" : [ "Halbelf", "Mensch-Elf Mischling" ],
    "half-goblin" : [ "Halbgoblin", "Mensch-Goblin Mischling" ],
    "half-ogre" : [ "Halboger", "Mensch-Oger Mischling. Ja das geht auch." ],
    "half-orc" : [ "Halborc", "Mensch-Orc Mischling" ],
    // Weapon skills / AT-listed weapon skills
    "melee-heavy": [ "Schwere Nahkampfwaffen", "Führung großer und schwerer Waffen, die zum Führen in erster Linie Kraft benötigen: Langschwerter, Breitäxte, Langäxte, Kriegshämmer, Morgensterne, oder Lanzen." ],
    "melee-medium": [ "Mittlere Nahkampfwaffen", "Führung von Waffen, für die sowohl Kraft als auch Wendigkeit benötigt wird: Kurzschwerter, Beile, Speere, Klingen-Stäbe, Sensen, usw." ],
    "melee-light": [ "Leichte Nahkampfwaffen", "Führung kleiner Waffen, die sehr schnell und wendig geführt werden: Dolche, Kettenhölzer, etc." ],
    "melee-fist": [ "Waffenloser Kampf", "Faustkampf, Karate, alles ist erlaubt." ],
    "bows": [ "Fernkampfwaffen", "Fernwaffen, bei denen es maßgeblich auf gutes Zielen, Vorhalten, und Abschätzung der Flugbahn ankommt: Bögen, Armbrüste, Ballisten, usw." ],
    "shields": [ "Schilde", "Verbesserte Technik mit Schilden zu blocken. Gilt sowohl für den Nahkampf als auch für Abwehr von Geschossen." ],
    "armor-wearing": [ "Rüstungen tragen", "Verbessert die Bewegungsfähigkeit in leichten oder schweren Rüstungen (reduziert die Rüstungsbehinderung)." ],
    // Magic
    "magic-neutral" : [ "Neutralmagie", "Allgemeine Magie, die jeder Magier erlernen kann. Sie ist unabhängig und urteilsfrei gegenüber anderen Magieschulen." ],
    "magic-life" : [ "Lebensmagie", "Magieschule des Lebens und des Lichts. Konzentriert erhaltende, helfende und heilende Kräfte, und stellt den Gegenpol zur Todesmagie dar." ],
    "magic-death" : [ "Todesmagie", "Dunkle, auf Erlangen von Macht ausgerichtete Magieschule. Sie agiert mit Vernichtung, qualvoller Desintegration, und Wiedererwecken von Toten zu gehorsamem Dienern." ],
    "magic-nature" : [ "Naturmagie", "Magieschule der Natur und der Erde. Sie erlaubt es, die elementaren Kräfte der Natur für Nützliches oder Schädliches solide zu formen." ],
    "magic-witchery" : [ "Hexermagie", "Magieschule, die sich den Elementen von Wind und Wasser, sowie der Sphäre von Geist und Gedanken befasst. Kann schützend un schädlich, unterstützend und manipulativ sein." ],
    "magic-chaos" : [ "Chaosmagie", "Magieschule der Veränderung, Unberechenbarkeit, Unordnung und Zerstörung. Zentriert um das Element Feuer." ],
    // Common skills
    "meditation": [ "Meditation", "Fähigkeit in ungestörten Ruhezeiten meditativ zu fokussieren. Das verbessert die Regeneration von Körper und Geist, und sammelt Kraft für kommende Ereignisse." ],
    "self-control": [ "Selbstbeherrschung", "Fähigkeit physische oder psychische Einwirkungen zu unterdrücken oder teilweise zu ignorieren, z.B. Schmerz, Lärm, Furcht/Angst, usw." ],
    "athletics": [ "Athletik", "Körperliche Fitness in Aufgaben, bei denen es dominierend auf Muskeln und Kondition ankommt: Laufen, Schwimmen, Springen, Sprinten, Klettern, usw." ],
    "acrobatics": [ "Akrobatik", "Körperliche Fitness und Technik in Aufgaben, bei denen Agilität und Wendigkeit im Vordergrund stehen: Parcours, Balance, Springen, Klettern, usw." ],
    "languages": [ "Sprachen", "Fähigkeit Fremdsprachen und Dialekte zu verstehen und zu sprechen. Mit zunehmendem Wert wird eigener Akzent und Sprechflüssigkeit besser." ],
    "trading": [ "Handeln", "Fähigkeit sich bei Geschäften nicht unterkriegen zu lassen, bessere Konditionen auszuhandeln, und den Wert von Waren einschätzen zu können. Verbessert auch den Zugang zu raren oder unpopulären Waren." ],
    "lexis": [ "Schriften & Runen", "Lehre des geschriebenen Wortes, d.h. Lesen und Schreiben von Manuskripten und Runen. Bezieht auch mit ein, Kernaussagen oder grundlegende Bedeutungen von unbekannten Texten aus dem bereits gelernten Fundus folgern zu können." ],
    "culture": [ "Gesellschaftswissen", "Charakterkontext abhängiges Wissen über Geschichte, Heraldik, Etiquette, kulturelle Traditionen, und Juristerei. Höhere Werte in dieser Fertigkeit erweitern stetig den Rahmen auf fremde Kulturräume." ],
    "rites": [ "Riten & Religion", "Wissen über Religionen, Riten, Bräuche, Kultismus, und rituelle Traditionen. Höhere Fertigkeitswerte ergeben stetig genauere Details in den eigenen Kontext, und tiefere Einblicke in fremde Religionen." ],
    "humanities": [ "Menschenkenntnis", "Wissen und praktische Erfahrung in der Essenz von Verstand und Unterbewusstsein. Verbessert es Lügen aufzudecken oder Aktionen anderer abschätzen zu können, sowie gekonnt zu beruhigen oder zu provozieren." ],
    "entertainment": [ "Unterhaltung", "Kunst andere gekonnt - auf die spezielle Weise des Charakters - zu unterhalten und Aufmerksamkeit auf sich zu ziehen. Z.B. durch Musizieren, Schauspielerei, Tanzen, Reden halten, oder Zaubertricks." ],
    "sneak": [ "Schleichen", "Fähigkeit, sich für normale Sinne unerkannt zu bewegen." ],
    "locks": [ "Schlösserkunde", "Wissen und praktische Erfahrung im Umgang mit Schlössern und Sicherheitsmechanismen. Umfasst Wissen über magische Sicherheitsmechanismen auch dann wenn der Charakter kein Magier ist." ],
    "traps": [ "Fallenkunde", "Kenntnisse und praktische Erfahrung über Fallen und Auslösemechanismen. Wissen über magische Fallen hat der Charakter auch dann wenn er kein Magier ist" ],
    "pickpocket": [ "Taschendiebstahl", "Fähigkeit unbemerkt Objekte vom Körper zu stehlen oder welche unterzujubeln." ],
    "alchemy": [ "Alchemie", "Theoretische und praktische Kenntnisse über alchemistische Stoffe, Zutaten, Wirkungen, Apparate, Verarbeitung und Braukunst." ],
    "medicine": [ "Heilkunde", "Wissen und Erfahrung über Heilkunst und Anatomie. Umfasst Erste Hilfe, Anwendung von Heilkräutern/-stoffen, Praktiken, Symptom-Bekämpfung, sowie Kenntnisse von physischen/psychischen/magischen Krankheitsbildern. Anatomische Kenntnisse steigen langsam mit dem Fertigkeitswert." ],
    "botany": [ "Pflanzenkunde", "Wissen und praktische Erfahrung über Pflanzen, sowie deren Vorkommen, Wirkungen, Behandlung, Verarbeitung, Kultivierung und Kreuzung" ],
    "engineering": [ "Ingenieurskunst", "Wissen über die Anwendung physischer/magischer Wirkprinzipien für Werkzeugbau, Kriegsgeräte, funktionale Architektur, Massenfertigung, u.Ä." ],
    "forging": [ "Schmieden & Grobhandwerk", "Praktische Hands-On Erfahrung in muskel-intensiven Handwerk wie Schmieden, Steinmetzkunst. Die künstlerische Wertigkeit der Produkte steigt mit dem Fertigkeitswert (zusätzlich zur Probenqualität)." ],
    "crafting": [ "Kunst & Feinhandwerk", "Praktische Erfahrung im Erzeugen handgefertigter filigraner/detaillierter/ansprechender Produkte. Dazu zählen Berufe wie Malen, Schneidern, Töpfern oder Feinschmieden." ],
    "camouflage": [ "Tarnen", "Wissen und Praxis im Tarnen, Verdecken und Verkleiden." ],
    "orientation": [ "Orientierung", "Erhöht den Sinn für Richtung, Wegfindung und den eigenen Standort. Gilt sowohl für die Natur als auch für große Städte." ],
    "instinct": [ "Instinkt", "Training oder Begabung im Deuten subtiler Eindrücke, mit der Gefahren oder Ungereimtheiten erkannt werden können." ],
    "wildlife": [ "Naturkunde", "Wissen über Flora und Fauna bzw. Lebensräume und deren Tier- und Pflanzenwelt. Umfasst Jagen, Überlebenskunst, Spurenlesen, und finden genießbarer Pflanzen. Kenntnisse über spezielle Wirkungen/Eigenschaften von Pflanzenteilen oder Tierorganen sind allerdings sehr rudimentär." ],
    "cooking": [ "Kochen", "Kunst des guten Geschmacks. Stärkend und \"moralisch wertvoll\"" ],
    "gambling": [ "Glückspiel & Zechen", "Die Kunst Spiele zu gewinnen, andere unter den Tisch zu trinken, und in der Taverne zu feiern bis der Arzt oder andere lokale Heilkundige angewankt kommen." ],
    "throwing": [ "Werfen", "Werfen von Gegenständen mit Kraft und Zielgenauigkeit." ],
    // Tools/Objects/Items
    "axe": [ "Axt", "" ],
  },

}}}})();
